- app.py
- migration_analysis.txt
- model/user.py
- pkg/common/user.py
- routes/auth.py
- routes/blueprint.py
- routes/build.py
- routes/cloning.py
- routes/conversion.py
- routes/discover.py
- routes/index.py
- routes/project.py
- routes/server.py
- routes/status.py
- routes/storage.py
- routes/stream.py
JWT authentication added to all end points
> JWT authentication added

- model/project.py
- model/user.py
- pkg/common/project.py
- routes/project.py
- routes/stream.py
Project user mapping is completed.
> project access restricted to logged in user

- app.py
- migration_analysis.txt
- model/project.py
- pkg/azure/location.py
- pkg/common/project.py
- routes/locations.py
- routes/project.py
- API for dynamically fetching azure locations added
- Project creation, update and fetch updated with new fields
> Dynamically fetching azure locations

- app.py
- migration_analysis.txt
- model/project.py
- pkg/aws/location.py
- pkg/azure/compute.py
- routes/locations.py
- routes/vm_types.py
API to fetch azure vm types added
> /vms/get api added

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- LICENSE
> license change

- Dockerfile
Fixed dependency with setuptools_rust in Dockerfile
> added new requirement setuptools_rust in dockerfile

- Dockerfile
Added environment variable to disable rust build
> Disabling RUST build by adding env variable

- pkg/azure/sas.py
Fixed SAS token authorization issue while downloading img
> updated sas token generator to fix authorization erros

- pkg/azure/network.py
update Ip after interface creation in azure
> azure ip update in DB

- pkg/aws/network.py
- pkg/azure/conversion_worker.py
- pkg/azure/network.py
> updated status codes for migration

- ansible/azure/azure_env_setup_redhat_7.yaml
testing is required. auth is missing
> azure redhat ansible init

- UI/xmigrate-ui/public/index.html
- UI/xmigrate-ui/src/components/Table/NetworkTable.js
- UI/xmigrate-ui/src/components/Table/SubnetTable.js
- UI/xmigrate-ui/src/pages/BluePrint/BluePrint.js
- UI/xmigrate-ui/src/pages/BluePrint/BluePrint.scss
- UI/xmigrate-ui/src/pages/Discover/Discover.scss
- UI/xmigrate-ui/src/pages/Project/Project.js
- Discovery scroll
- GCP file upload
-  Modal CloseButton
> UI Changes

- UI/xmigrate-ui/src/pages/Project/Project.js
- UI/xmigrate-ui/src/services/PostService.js
> - GCP Project Creation

- pkg/common/build.py
- pkg/gcp/disk.py
gcp disk clone and convert functions added
> gcp disk clone and convert added

- UI/xmigrate-ui/src/components/Table/NetworkTable.js
- UI/xmigrate-ui/src/pages/BluePrint/BluePrint.js
- UI/xmigrate-ui/src/pages/Project/Project.js
> GCP UI Changes

- UI/xmigrate-ui/src/pages/BluePrint/BluePrint.js
- UI/xmigrate-ui/src/pages/BluePrint/BluePrint.scss
- Alert moved to the right side
- Committing Network Disable button
> Commiting Alert Changes

- UI/xmigrate-ui/src/components/Table/HostTable.js
- UI/xmigrate-ui/src/pages/BluePrint/BluePrint.js
- Committing Disk column 
- Alert Committing
> Commiting Changes of Disk,Alert

- UI/xmigrate-ui/src/pages/BluePrint/BluePrint.js
- UI/xmigrate-ui/src/pages/Settings/Settings.js
- UI/xmigrate-ui/src/pages/Settings/Settings.scss
- Updated Status Code
- Updated Setting GCP 
- Updated Alert Settings
> Commiting Ui Changes

- UI/xmigrate-ui/src/pages/BluePrint/BluePrint.js
- Progress Change Updates
- Button Build Progress Changes
> Commiting Changes

- ansible/azure/azure_env_setup_redhat_7.yaml
- ansible/gcp/gcp_env_setup_redhat_7.yaml
`pyinstaller footprint.py --onefile`
Created binary executable for footprint.py
> created freeze file for footprint.py

- UI/xmigrate-ui/src/components/Table/NetworkTable.scss
- UI/xmigrate-ui/src/pages/BluePrint/BluePrint.js
- UI/xmigrate-ui/src/pages/BluePrint/BluePrint.scss
- UI/xmigrate-ui/src/pages/Discover/Discover.js
- UI/xmigrate-ui/src/pages/Discover/Discover.scss
- UI/xmigrate-ui/src/pages/SignIn/SignIn.js
- UI/xmigrate-ui/src/pages/SignIn/SignIn.scss
- UI Enhancement Blueprint,Network,Sign in
> Commiting UI Enhancements

- README.md
- ansible/gcp/gcp_env_setup_redhat_7.yaml
- ansible/gcp/gcp_env_setup_ubuntu_16.yaml
- ansible/gcp/gcp_env_setup_ubuntu_18.yaml
- ansible/gcp/gcp_env_setup_ubuntu_20.yaml
- ansible/gcp/xmigrate.yaml
- ansible/payloads/start_dd_gcp.py
- pkg/gcp/disk.py
Added support for below OS's for GCP migration
- Ubuntu 16.04/18.04/20.04
- Redhat 7/8
> added ubuntu support for GCP migration

- pkg/aws/disk.py
- pkg/aws/network.py
- pkg/gcp/disk.py
- utils/playbook.py
Fixed the cloning threads getting blocked issue and converted playbook execution calls to python.
> fix: cloning blockages

- ansible/aws/gather_facts.yaml
- ansible/azure/gather_facts.yaml
- ansible/gcp/gather_facts.yaml
- model/discover.py
- routes/discover.py
- utils/log_reader.py
- utils/playbook.py
Now gathering the system facts with ansible instead of binary.
> gather facts with ansible

- pkg/azure/conversion_worker.py
- pkg/azure/disk.py
- pkg/azure/network.py
- pkg/azure/resource_group.py
- pkg/common/project.py
- routes/blueprint.py
- routes/master.py
- routes/project.py
Fixing the download location for azure disk downloads and pointing them to ./projects/{project}/{host}/osdisks/ directory.
Changed the cloning call method to ansible_runner call from cli call to fix the thread blockage problem as well.
This pr should come after [https://github.com/xmigrate/xmigrate/pull/194](url)
> fix: azure disk download location

- pkg/aws/ami.py
- pkg/aws/creds.py
- pkg/common/build.py
- utils/playbook.py
Changed the role permission policies to fix the insufficient permissions issue.
> fix: AWS IAM role permission issues

- ansible/aws/gather_facts.yaml
- ansible/azure/gather_facts.yaml
- ansible/gcp/gather_facts.yaml
- pkg/aws/creds.py
- routes/discover.py
Makes the command work universally.
> fix: lsblk PATH column not available issue

- ansible/azure/azure_env_setup_centos_7.yaml
- ansible/azure/azure_env_setup_redhat_7.yaml
- ansible/azure/azure_env_setup_redhat_8.yaml
- ansible/azure/azure_env_setup_ubuntu_16.yaml
- ansible/azure/azure_env_setup_ubuntu_18.yaml
- ansible/azure/azure_env_setup_ubuntu_20.yaml
Install wget just in case so that downloading azcopy won't fail
> Install wget in azure if not present

- pkg/common/network.py
- pkg/gcp/compute.py
- pkg/gcp/disk.py
Fixes the issues currently present with gcp vm build process.
fixes #211
> fix: gcp build issues

- UI/xmigrate-ui/src/services/Services.js
- pkg/azure/compute.py
- pkg/azure/conversion_worker.py
- pkg/azure/disk.py
- pkg/common/build.py
Fixes the current blockages azure conversion is facing. Minor cleanup and fail conditions included.
closes #213
> fix: azure conversion blockages

- Dockerfile
- ansible/aws/aws_env_setup_centos_7.yaml
- ansible/aws/aws_env_setup_centos_8.yaml
- ansible/aws/aws_env_setup_redhat_7.yaml
- ansible/aws/aws_env_setup_redhat_8.yaml
- ansible/aws/aws_env_setup_ubuntu_16.yaml
- ansible/aws/aws_env_setup_ubuntu_18.04.yaml
- ansible/aws/aws_env_setup_ubuntu_20.yaml
- requirements.txt
Configures kernel in AWS cloud targets. Also Dockerfile updated and added netaddr dependency.
> Changes for release

- Dockerfile
- pkg/aws/ec2.py
Detect the system architecture and download a compatible azcopy version.
> fix: azcopy in dockerfile isn't architecture-agnostic

- Dockerfile
- pkg/aws/ec2.py
Download architecture compatible azcopy version and makes sure there aren't grammar issues
> fix: azcopy in dockerfile isn't architecture-agnostic (re)

- .github/workflows/build.yaml
- Dockerfile
Github workflow for automatic build and push of multiplatform docker images on version release.
closes #229
> feat: docker image build and push workflow

- ansible/aws/aws_env_setup_ubuntu_22.yaml
- ansible/aws/xmigrate.yaml
Added ubuntu 22.04 ansible playbook for aws migration.
Related to #238
> added support for aws-ubuntu 22.04

- pkg/common/cloning.py
- pkg/common/vm_preparation.py
- routes/discover.py
- utils/database.py
- utils/playbook.py
Finally effectively enables all playbook runs to use a single method, and fixes some behaviors regarding the execution. Also changes the db session to be managed by a context manager instead of managing it manually.
fixes #247
> fix: ansible playbook execution quirks fixes
